project:
  type: book

book:
  title: "The Hitchhikers Guide to R"
  author: 
    - Greg Martin 
    - Andrew Gard
    - Luca Martial
  date: "9/18/2022"
  page-navigation: true
  number-depth: 1
  chapters:
    - index.qmd
    - first_session.qmd
    - exploring data visually.qmd
    - exploring data quantitatively.qmd
    - practical data science with r.qmd
    - case study 1.qmd
    - manipulating data.qmd
    - cleaning data.qmd
    - modeling data.qmd
    - case study 2.qmd
    - presenting data.qmd
    - getting technical.qmd
    - case study 3.qmd
    - references.qmd
  appendices: 
    - errors.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

